# Generated by Django 6.1.1 on 2026-09-08 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 8, 11, 1, 2, 680340, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
