# Generated by Django 6.1.1 on 2026-09-11 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active'], name='listings_li_is_acti_03d721_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location'], name='listings_li_locatio_4bc07d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['rooms'], name='listings_li_rooms_4641e1_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['housing_type'], name='listings_li_housing_6b3577_idx'),
        ),
    ]
