# Generated by Django 6.1.1 on 2026-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options_alter_listingphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
