# Generated by Django 6.1.1 on 2026-09-10 07:51

import django.core.validators
import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_deleted_at_listingphoto_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
