# Generated by Django 6.1.1 on 2026-09-10 08:07

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
